version: '3.8'

services:
  nodejs:
    build: 
      context: ./
      dockerfile: ./dockerfiles/node/Dockerfile
    volumes:
      - ./:/app
      - ./app/node_modules
    ports:
      - "3000:3000"
